### ISSUE TITLE
General power switch of electrical cabinet for roof and walls controls goes off often after operations

### ISSUE THREAD

**Issue by simonegarrappa** [blumzi/LAST_issues#30] opened 2024-02-08 22:54 UTC
On the visit of 08-02-2024 the electric cabinet with roof and walls controls was found switched off at arrival. 
After re-activating it, it switched off after non-regular time periods that ranged from 10-15 minutes to 30 minutes. 

During some tests, it never switched off during opening/closing of roof and walls, but only afterwards and at least after 10-15 minutes. 

During some tests the UPS was reporting an overloading error (Error 43 on display). Disconnecting the cabinet from the UPS didn't solve the issue. 

@EastEriq  may add more details and thougths for the records.

NOTE: AC is also not powered in these cases, and it might be a serious problem when day temperatures will raise in spring.

**Comment by EastEriq** [comment] 2024-02-09 09:23
Just adding details: The general safety switch of the enclosure control cabinet is labelled FU, and sits inside the cabinet at mid height, just right of the blue UPS three-position commutator. It is rated for 8A, i.e. 1.7kW. That was a generous margin with the old roof motor provided by Shushan (380W) + some 150W of load of all other motors + PLC.
Since Yossi changed the roof motor, and installed a "three-phase electromechanical repeater" about which I have no information, I can't comment on power  requirements. The new setting has worked for a while, so we may have ran into a new problem. To my understanding the protection is only for overcurrent, not for ground dispersion, so it is less probable that the problem is due to loss of insulation because of water infiltration.

Simone tested the movement of all sections individually, and none seemed to cause an immediate overcurrent; nor he found any sign of PLC, power supplies or motor cabinet overheating or humming anomalously. However, the problem seems to have appeared "spontaneously", even with no section moving. Spontaneously is a relative concept, because the PLC may command automatic closing at a power outage, running on UPS.

Nora had already ran into the problem two weeks ago, and reported the UPS beep. The cabinet has been off during the whole last week, since the last visit.

To avoid future nuisances, I instructed Simone to turn the blue commutator on Mains only. That means that we won't have automatical closing. Given the status, the roof is certainly not fit for remote operation.

**Comment by simonegarrappa** [comment] 2024-02-10 21:25
Updates from the two days of observations: 08/09 - Feb 2024

- The roof and wall sections operated without issues. The closing sequence was always 1-rising walls (one by one) ad 2-Roof. Shortly after the roof was closed (1-2 minutes) the general safety switch goes off. 
- After re-activating power, it was still on at the start of the operation on the following night.
- Same thing happened at the end of operations on the second night, and the power was still on when we left the observatory to return in Rehovot at ~11 am on Feb 10.

-The shut-down of the general safety switch didn't happen after opening operations of roof and wall sections.

**Comment by EastEriq** [comment] 2024-03-06 08:42
The consensus as of today about this is:

- toward the end of the closing flight, the North cup cog connecting the roof motor to the actuation axle disengages, because the axle is allowed to slide axially inside the bearing
![image](https://github.com/blumzi/LAST_issues/assets/16066531/70eb44e0-5b59-40d9-8705-d2c261e54af2)
- probably a holding screw is missing, or loose
![image](https://github.com/blumzi/LAST_issues/assets/16066531/8ae151ca-1133-4d22-8afc-cb5609868409)
- once the cog is disengaged, the roof is pulled asymmetrically, dragging more current from the motor, which causes the breaker to jump.
The temporary cure is to force the axle back in place:
![image](https://github.com/blumzi/LAST_issues/assets/16066531/7a03b047-26f9-48c1-a65e-3ef38360e07e)

**Closed** 2024-05-28 09:10 UTC
