### ISSUE TITLE
INPOP ephemerides missing for M1

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#20] opened 2024-01-25 22:38 UTC
Unit=obs.unitCS('01')
{inst.XerxesMountBinary} the INPOP ephemerides were not found, doing without

**Comment by EastEriq** [comment] 2024-01-26 05:27
As of now INPOP is only needed for goToTarget2, where installed, so this is a harmless warning for current operations. But since this is the direction we are moving to, good that the problem is flagged and brought to attention

**Comment by noralinn** [comment] 2024-01-26 10:15
I wanted to calculate and test a pointing for a second mount (in addition to M10), but all had issues. (INPOP missing, images not saved, focuser not working).

Pointing model on M10 is good! I'll test it another time and then we should move to goToTarget2 and get pointing models for other mounts.

**Comment by EastEriq** [comment] 2024-01-28 14:47
Solved by Sasha half an hour ago

**Closed by EastEriq** 2024-01-28 14:47 UTC
